### ISSUE TITLE
Memory issues on large uploads

### ISSUE THREAD

**Issue by etherwvlf** [git001/caddyv2-upload#2]
I am experiencing strange issues where memory load becomes monstrous when uploading large files. 
It starts normal and slowly but steadily process memory grows to explicit amounts.

This for example is the result when uploading 10GB file, around 80-90% of upload completion:
![DeepinScreenshot_select-area_20220524233104](https://user-images.githubusercontent.com/37346176/170549882-4e084cbb-d8dd-4624-bced-1502c1dc0a9a.png)

Sometimes memory load hovers around 8-10GB sometimes  it goes all the way up to:
![DeepinScreenshot_select-area_20220526213225](https://user-images.githubusercontent.com/37346176/170553628-08cab374-bec1-4a24-a6d4-a520a8b5b2af.png)

I am using this config for testing, but I don't think it is related to an error in the config, as everything works fine and dandy for small files.

```
{
	http_port 8888
	admin off
	order upload before file_server
}

:8888 {
	root .

	encode zstd gzip

	file_server /upload/* {
		browse upload.htm
	}

	file_server /* browse

	@mypost method POST
	upload @mypost {
		dest_dir upload
		max_filesize 15G
		response_template upload-resp.txt
	}

	log {
		output file access.log
	}
}
```
As long as you use something big and upload it continuously for enough time this can be reproduced, as I have tried with different size and types of files. Doesn't matter if I use my JS upload form or simply POST-ing with curl the result is the same.
After completing upload, the process retains this memory loaded state for some time and returns to around 400-900MB memory usage after a while which also seems rather much to me for an idle process.

**Comment by git001** [comment]
Yep, this is because of ReadAll call, should be fixed with this commit https://github.com/git001/caddyv2-upload/commit/aa4681e2acade1ce993b19f84823afe8d7fb92e7  
Please can you use the latest image if you use docker hub images.

**Comment by etherwvlf** [comment]
I don't use docker, but I will build right away with xcaddy and make some tests.

**Comment by etherwvlf** [comment]
I am testing with the new build but unfortunately the issue still persists.
This is from uploading 10G file at around 70 percent complete:
![70perc](https://user-images.githubusercontent.com/37346176/170608352-df58a862-e90b-4e33-b92c-9574721d4ab8.png)

**Comment by git001** [comment]
Please test the new version `0.4` and set the parameter `max_form_buffer` to limit the memory usage.

**Comment by etherwvlf** [comment]
Sorry, I couldn't respond promptly as I had some business to attend to.
It would seem like this is still an issue:
![DeepinScreenshot_select-area_20220527070254](https://user-images.githubusercontent.com/37346176/170698417-c0ee1e40-769f-4fe0-8fdf-d946ee7482be.png)

However this time it builds up to around 5-6GB, stays there for some time and then memory usage drops to 200-300MB throughout the rest of the upload process.
I am using ```max_form_buffer``` set to 1GB and the same config as my original post. I have tried different values to no avail.
Maybe it doesn't honor the ```max_form_buffer``` parameter ?

**Comment by git001** [comment]
Well it looks like deep in side the go modules are some more copy parts

https://cs.opensource.google/go/go/+/refs/tags/go1.18.2:src/net/http/request.go;l=1299;bpv=0;bpt=1

```
ParseMultipartForm
  -> ParseForm
    -> copyValues
```

This parts have no limits as far as I see.

> However this time it builds up to around 5-6GB, stays there for some time and then memory usage drops to 200-300MB throughout the rest of the upload process.

With this statement you mean that only when the upload starts is that high amount of memory used and after some time not more?

**Comment by etherwvlf** [comment]
I mean when the upload is started memory usage slowly and steadily goes all the way up to 5-6GB, retains this level for a time and then suddenly drops to 200-300MB which sustains for the rest of the upload.

**Comment by etherwvlf** [comment]
I found something interesting -
If I set ```max_form_buffer``` to 100MB, memory usage climbs to around 700-800MB, retains this level for some time and then drops to 60-70MB. Could it be that the size of this buffer parameter is incorrectly interpreted ?
I will now test it with ```max_form_buffer``` 50MB to see what happens.

**Comment by etherwvlf** [comment]
Yep, this must be it, it climbs to:
![DeepinScreenshot_select-area_20220527070254](https://user-images.githubusercontent.com/37346176/170706486-64e7fd9b-2cd5-4cf4-8bc6-bfec61ad9b08.png)
And after a while:
![second](https://user-images.githubusercontent.com/37346176/170706696-b12c18be-1839-43ac-bd40-7c1a4d6f1c06.png)
Quite better I must say.

**Comment by git001** [comment]
Well observation, thank you for your detailed information and that you use the module :smile:  
Looks like the `max_form_buffer` is multiplied by 7-8 Times.

Please tell me when we can close this issue with a proper outcome.
I will then add the outcome to the https://github.com/git001/caddyv2-upload#background-informations

**Comment by etherwvlf** [comment]
As far as I am concerned it can be closed now.
Thank you for writing this module as it really has been a life saver and much needed addition to the plugin kingdom.

**Comment by git001** [comment]
@etherwvlf I have created https://github.com/git001/golang-multiparttest to verify the upload behavior. looks like the Memory usage is quite normal.

**Comment by etherwvlf** [comment]
I haven't yet used your tool but here are some more tests on my part...
I have set the buffer at ```max_form_buffer = 100MB```

When uploading 3GB single file:
![single_file](https://user-images.githubusercontent.com/37346176/170846531-d718396f-0043-4428-9aa3-edc85fe4d833.png)
When uploading 2x3GB files:
![2_files](https://user-images.githubusercontent.com/37346176/170846575-b997ba5f-50d7-4f18-80a3-5edbeb32c886.png)
When uploading 3x3GB files:
![3_files](https://user-images.githubusercontent.com/37346176/170846653-e9f8f428-a8ac-43c7-9865-13bda17339f0.png)
When uploading 4x3GB files:
![4_files](https://user-images.githubusercontent.com/37346176/170846692-11effc8d-7c33-49fb-98c6-6592a259347e.png)
When uploading 5x3GB files:
![5_files](https://user-images.githubusercontent.com/37346176/170846750-60ae9c34-201b-4449-a2ca-105136d8d759.png)
When uploading 6x3GB files:
![6_files](https://user-images.githubusercontent.com/37346176/170846844-b160d494-307e-4d86-a873-3507dd448021.png)

It seems to be directly linked to the number of uploaded files at one time A.K.A. multipart upload.
But no matter how high the initial memory load is, after a while it goes back to normal so all is fine by me:
![DeepinScreenshot_select-area_20220529041929](https://user-images.githubusercontent.com/37346176/170848086-13a2da21-d232-444e-997b-7ec8fa6f21a5.png)

**Comment by git001** [comment]
This issue could be solved with this commit https://github.com/golang/go/issues/58363
